### ISSUE TITLE
Error using segmentation models on RTX 4080 GPU

### ISSUE THREAD

**Issue by ntjess** [SixK/coco-annotator-ng#9]
Thanks for providing this software! I attempted to follow the build and run instructions for the zim model. I see this stack trace after running `docker compose -f ./docker-compose.dev.yml up`:

<details>

```
[2024-11-19 06:49:44 +0000] [29] [ERROR] Exception in worker process
annotator_ia         | Traceback (most recent call last):
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
annotator_ia         |     worker.init_process()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 142, in init_process
annotator_ia         |     super().init_process()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 135, in init_process
annotator_ia         |     self.load_wsgi()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
annotator_ia         |     self.wsgi = self.app.wsgi()
annotator_ia         |                 ^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
annotator_ia         |     self.callable = self.load()
annotator_ia         |                     ^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
annotator_ia         |     return self.load_wsgiapp()
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
annotator_ia         |     return util.import_app(self.app_uri)
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
annotator_ia         |     mod = importlib.import_module(module)
annotator_ia         |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
annotator_ia         |     return _bootstrap._gcd_import(name[level:], package, level)
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
annotator_ia         |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
annotator_ia         |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
annotator_ia         |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
annotator_ia         |   File "/workspace/ia/__init__.py", line 14, in <module>
annotator_ia         |     from .api import blueprint as api
annotator_ia         |   File "/workspace/ia/api/__init__.py", line 6, in <module>
annotator_ia         |     from .models import api as ns_models
annotator_ia         |   File "/workspace/ia/api/models.py", line 20, in <module>
annotator_ia         |     from ..util.sam2 import model as sam2
annotator_ia         |   File "/workspace/ia/util/sam2.py", line 52, in <module>
annotator_ia         |     model = SAM2()
annotator_ia         |             ^^^^^^
annotator_ia         |   File "/workspace/ia/util/sam2.py", line 22, in __init__
annotator_ia         |     self.sam2_model=build_sam2(SAM2_MODEL_CONFIG, ckpt_path=SAM2_MODEL_PATH, device=AnnotatorConfig.DEVICE)
annotator_ia         |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/sam2/build_sam.py", line 94, in build_sam2
annotator_ia         |     model = model.to(device)
annotator_ia         |             ^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1174, in to
annotator_ia         |     return self._apply(convert)
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
annotator_ia         |     module._apply(fn)
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
annotator_ia         |     module._apply(fn)
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
annotator_ia         |     module._apply(fn)
annotator_ia         |   [Previous line repeated 1 more time]
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
annotator_ia         |     param_applied = fn(param)
annotator_ia         |                     ^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in convert
annotator_ia         |     return t.to(
annotator_ia         |            ^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
annotator_ia         |     torch._C._cuda_init()
annotator_ia         | RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
annotator_ia         | [2024-11-19 06:49:44 +0000] [29] [INFO] Worker exiting (pid: 29)
annotator_ia         | zz info: configs/sam2.1/sam2.1_hiera_b+.yaml /models/sam2.1_hiera_base_plus.pt cuda
annotator_ia         | [2024-11-19 06:49:44 +0000] [27] [ERROR] Worker (pid:29) exited with code 3
annotator_ia         | [2024-11-19 06:49:44 +0000] [27] [ERROR] Shutting down: Master
annotator_ia         | [2024-11-19 06:49:44 +0000] [27] [ERROR] Reason: Worker failed to boot.
annotator_ia exited with code 3
```

</details>

Is this and SAM2 designed to work with RTX 4080?

Output of `nvidia-smi`:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4080        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   47C    P8              13W / 320W |     85MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   3290860      G   /usr/lib/xorg/Xorg                           56MiB |
|    0   N/A  N/A   3290898      G   /usr/bin/gnome-shell                         21MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by SixK** [comment]
OK, weird problem, I have actually no real clue.

Can you try such command `python -c "import torch; print(torch.cuda.is_available())"` outside and inside docker ? (pytorch has to be installed on your system (in a virtualenv should be ok)

Note if Sam2 is the problem, you can disable it changing this line in docker-compose.dev.yml file:
      `- SAM2="1"` by  `      - SAM2="0"`

and commenting this 2 lines:
      - SAM2_MODEL_FILE=/models/sam2.1_hiera_base_plus.pt
      - SAM2_MODEL_CONFIG=configs/sam2.1/sam2.1_hiera_b+.yaml

Latest added tool called Zim is at least as good as Sam2.

Here is a page that could help you to understand the problem:
https://discuss.pytorch.org/t/runtimeerror-unexpected-error-from-cudagetdevicecount/139977

Another page with some different solutions:
https://stackoverflow.com/questions/66857471/cuda-initialization-cuda-unknown-error-this-may-be-due-to-an-incorrectly-set

**Comment by ntjess** [comment]
Outside docker works on py311:
```python
In [1]: import torch

In [2]: torch.tensor([1,2,3], device="cuda").device
Out[2]: device(type='cuda', index=0)
```

Which docker entrypoint did you want me to test? It works well in a vanilla yolov8 training context: https://hub.docker.com/r/ultralytics/ultralytics


> Latest added tool call Zim is at least as good as Sam2.

This error occurs on Zim too:

<details>

```
annotator_ia         | [2024-11-19 16:48:02 +0000] [29] [ERROR] Exception in worker process
annotator_ia         | Traceback (most recent call last):
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
annotator_ia         |     worker.init_process()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 142, in init_process
annotator_ia         |     super().init_process()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 135, in init_process
annotator_ia         |     self.load_wsgi()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
annotator_ia         |     self.wsgi = self.app.wsgi()
annotator_ia         |                 ^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
annotator_ia         |     self.callable = self.load()
annotator_ia         |                     ^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
annotator_ia         |     return self.load_wsgiapp()
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
annotator_ia         |     return util.import_app(self.app_uri)
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
annotator_ia         |     mod = importlib.import_module(module)
annotator_ia         |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
annotator_ia         |     return _bootstrap._gcd_import(name[level:], package, level)
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
annotator_ia         |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
annotator_ia         |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
annotator_ia         |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
annotator_ia         |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
annotator_ia         |   File "/workspace/ia/__init__.py", line 14, in <module>
annotator_ia         |     from .api import blueprint as api
annotator_ia         |   File "/workspace/ia/api/__init__.py", line 6, in <module>
annotator_ia         |     from .models import api as ns_models
annotator_ia         |   File "/workspace/ia/api/models.py", line 32, in <module>
annotator_ia         |     from ..util.zim import model as zim
annotator_ia         |   File "/workspace/ia/util/zim.py", line 49, in <module>
annotator_ia         |     model = ZIM()
annotator_ia         |             ^^^^^
annotator_ia         |   File "/workspace/ia/util/zim.py", line 20, in __init__
annotator_ia         |     zim_model.cuda()
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/zim_anything/modeling/zim.py", line 84, in cuda
annotator_ia         |     super(Zim, self).cuda(device)
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 916, in cuda
annotator_ia         |     return self._apply(lambda t: t.cuda(device))
annotator_ia         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
annotator_ia         |     module._apply(fn)
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
annotator_ia         |     param_applied = fn(param)
annotator_ia         |                     ^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
annotator_ia         |     return self._apply(lambda t: t.cuda(device))
annotator_ia         |                                  ^^^^^^^^^^^^^^
annotator_ia         |   File "/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
annotator_ia         |     torch._C._cuda_init()
annotator_ia         | RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
annotator_ia         | [2024-11-19 16:48:02 +0000] [29] [INFO] Worker exiting (pid: 29)
annotator_ia         | [2024-11-19 16:48:03 +0000] [27] [ERROR] Worker (pid:29) exited with code 3
annotator_ia         | [2024-11-19 16:48:03 +0000] [27] [ERROR] Shutting down: Master
annotator_ia         | [2024-11-19 16:48:03 +0000] [27] [ERROR] Reason: Worker failed to boot.
```

</details>


> Here is a page that could help you to understand the problem:

Thanks for the resources. It looks like most of those people have problems running cuda-enabled torch on their system generically, which is not the case for me. I only see these problems in the docker environment for `coco-annotator-ng`...

**Comment by SixK** [comment]
To my side I have this nvidia/cuda drivers (on Ubuntu 22.04) :
```
NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4 
```
I think you can upgrade, I actually have no AI application having problems with this drivers.

Have a look at [backend/ia/Dockerfile](https://github.com/SixK/coco-annotator-ng/blob/main/backend/ia/Dockerfile), I had to move from `FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime` to `FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel`. In your case, you may try to use `FROM pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel` instead. (There is no cuda 12.2 docker image for pytorch). This will be more compatible with your 12.2 Cuda version.

Also note in Dockerfile, I had to add `apt install libcudnn9-cuda-12` for Zim to use GPU.

When AI container start, you may notice some cuda warnings (some potential missing cuda libraries).  
It seem's to have no impact but it also could be related to your problem.

**Comment by ntjess** [comment]
Thanks for your feedback. I updated my gpu drivers to 12.4 and it indeed fixed the problem!
